package ru.karapetiandav.ya_translator.models.translatorApi;

import java.util.HashMap;
import java.util.Map;

public class Langs {

    private static final String TAG = Langs.class.getSimpleName();
    public String af;
    public String am;
    public String ar;
    public String az;
    public String ba;
    public String be;
    public String bg;
    public String bn;
    public String bs;
    public String ca;
    public String ceb;
    public String cs;
    public String cy;
    public String da;
    public String de;
    public String el;
    public String en;
    public String eo;
    public String es;
    public String et;
    public String eu;
    public String fa;
    public String fi;
    public String fr;
    public String ga;
    public String gd;
    public String gl;
    public String gu;
    public String he;
    public String hi;
    public String hr;
    public String ht;
    public String hu;
    public String hy;
    public String id;
    public String is;
    public String it;
    public String ja;
    public String jv;
    public String ka;
    public String kk;
    public String kn;
    public String ko;
    public String ky;
    public String la;
    public String lb;
    public String lt;
    public String lv;
    public String mg;
    public String mhr;
    public String mi;
    public String mk;
    public String ml;
    public String mn;
    public String mr;
    public String mrj;
    public String ms;
    public String mt;
    public String ne;
    public String nl;
    public String no;
    public String pa;
    public String pap;
    public String pl;
    public String pt;
    public String ro;
    public String ru;
    public String si;
    public String sk;
    public String sl;
    public String sq;
    public String sr;
    public String su;
    public String sv;
    public String sw;
    public String ta;
    public String te;
    public String tg;
    public String th;
    public String tl;
    public String tr;
    public String tt;
    public String udm;
    public String uk;
    public String ur;
    public String uz;
    public String vi;
    public String xh;
    public String yi;
    public String zh;
    private Map<String, String> langs = new HashMap<>();

    public Map<String, String> getLangs() {
        langs.put("az", az);
        langs.put("ba", ba);
        langs.put("be", be);
        langs.put("bg", bg);
        langs.put("bn", bn);
        langs.put("bs", bs);
        langs.put("ca", ca);
        langs.put("ceb", ceb);
        langs.put("cs", cs);
        langs.put("cy", cy);
        langs.put("da", da);
        langs.put("de", de);
        langs.put("el", el);
        langs.put("en", en);
        langs.put("eo", eo);
        langs.put("es", es);
        langs.put("et", et);
        langs.put("eu", eu);
        langs.put("fa", fa);
        langs.put("fi", fi);
        langs.put("fr", fr);
        langs.put("ga", ga);
        langs.put("gd", gd);
        langs.put("gl", gl);
        langs.put("gu", gu);
        langs.put("he", he);
        langs.put("hi", hi);
        langs.put("hr", hr);
        langs.put("ht", ht);
        langs.put("hu", hu);
        langs.put("hy", hy);
        langs.put("id", id);
        langs.put("is", is);
        langs.put("it", it);
        langs.put("ja", ja);
        langs.put("jv", jv);
        langs.put("ka", ka);
        langs.put("kk", kk);
        langs.put("kn", kn);
        langs.put("ko", ko);
        langs.put("ky", ky);
        langs.put("la", la);
        langs.put("lb", lb);
        langs.put("lt", lt);
        langs.put("lv", lv);
        langs.put("mg", mg);
        langs.put("mhr", mhr);
        langs.put("mi", mi);
        langs.put("mk", mk);
        langs.put("ml", ml);
        langs.put("mn", mn);
        langs.put("mr", mr);
        langs.put("mrj", mrj);
        langs.put("ms", ms);
        langs.put("mt", mt);
        langs.put("ne", ne);
        langs.put("nl", nl);
        langs.put("no", no);
        langs.put("pa", pa);
        langs.put("pap", pap);
        langs.put("pl", pl);
        langs.put("pt", pt);
        langs.put("ro", ro);
        langs.put("ru", ru);
        langs.put("si", si);
        langs.put("sk", sk);
        langs.put("sl", sl);
        langs.put("sq", sq);
        langs.put("sr", sr);
        langs.put("su", su);
        langs.put("sv", sv);
        langs.put("sw", sw);
        langs.put("ta", ta);
        langs.put("te", te);
        langs.put("tg", tg);
        langs.put("th", th);
        langs.put("tl", tl);
        langs.put("tr", tr);
        langs.put("tt", tt);
        langs.put("udm", udm);
        langs.put("uk", uk);
        langs.put("ur", ur);
        langs.put("uz", uz);
        langs.put("vi", vi);
        langs.put("xh", xh);
        langs.put("yi", yi);
        langs.put("zh", zh);

        return langs;
    }
}